apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-backend
  labels:
    app: task-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
        - name: backend
          image: task-manager-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://taskuser:taskpass@192.168.49.1:5432/taskdb"
            - name: MONGO_URL
              value: "mongodb://192.168.49.1:27017"
            - name: MONGO_DB
              value: taskdb
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20